import java.time.LocalTime;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author raull
 */
public class Consultas extends javax.swing.JPanel {

    private String eleccion = "";

    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBoxConsultas = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 204, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("CONSULTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxConsultas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matrícula de los vehículos cuyo año de fabricación (afabricación) sea el 2024", "Marca y modelo de los vehículos que tengan menos de 75000 kilómetros.", "Nombre y apellidos de los propietarios que tengan un Golf.", "Nombre y apellidos de todos los mecánicos de vehículos." }));
        jComboBoxConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jComboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConsultasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a = "Matrícula de los vehículos cuyo año de fabricación (afabricación) sea el 2024";
        String b = "Marca y modelo de los vehículos que tengan menos de 75000 kilómetros.";
        String c = "Nombre y apellidos de los propietarios que tengan un Golf.";
        String d = "Nombre y apellidos de todos los mecánicos de vehículos.";
        ConsultasBaseDatos abrirBase = new ConsultasBaseDatos();
        String rutaConsulta = "./AD52425/Ejercicio02A.xq";

        if (jComboBoxConsultas.getSelectedItem().equals(a)) {
            rutaConsulta = "AD52425/Ejercicio02A.xq";
            eleccion = "a";
        }
        if (jComboBoxConsultas.getSelectedItem().equals(b)) {
            rutaConsulta = "AD52425/Ejercicio02B.xq";
            eleccion = "b";
        }
        if (jComboBoxConsultas.getSelectedItem().equals(c)) {
            rutaConsulta = "AD52425/Ejercicio02C.xq";
            eleccion = "c";
        }
        if (jComboBoxConsultas.getSelectedItem().equals(d)) {
            rutaConsulta = "AD52425/Ejercicio02D.xq";
            eleccion = "d";
        }

        String consultaImpresa = abrirBase.leerArchivo(rutaConsulta);
        String resultado = abrirBase.AbrirBaseDatos(consultaImpresa);
        monstrarResultados(resultado);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void monstrarResultados(String resultado) {
        Vector<String> tableHeader = new Vector<String>();
        Vector tableData = new Vector();
        String resultadoLimpio = resultado.replace("\n", " ");
        String[] campos = resultadoLimpio.split(" ");

        if (eleccion == "a") {
            tableHeader.add("Matricula");

            for (String matricula : campos) { // Recorremos todos los valores correctamente
                Vector<String> onRow = new Vector<>();
                onRow.add(matricula);
                tableData.add(onRow);
            }

        }
        if (eleccion == "b") {
            tableHeader.add("Marca");
            tableHeader.add("Modelo");

            String marca = "";
            String modelo = "";

          
            for (int i = 0; i < campos.length; i++) {
                Vector<String> onRow = new Vector<String>();
                if (i % 2 == 0) { 
                    marca = campos[i];
                } else {  
                    modelo = campos[i];

                    
                    onRow.add(marca);
                    onRow.add(modelo);
                    tableData.add(onRow);
                }
            }

        }
        if (eleccion == "c") {
            tableHeader.add("Nombre");
            tableHeader.add("Apellidos");

             String marca = "";
            String modelo = "";

          
            for (int i = 0; i < campos.length; i++) {
                Vector<String> onRow = new Vector<String>();
                if (i % 2 == 0) { 
                    marca = campos[i];
                } else {  
                    modelo = campos[i];

                    
                    onRow.add(marca);
                    onRow.add(modelo);
                    tableData.add(onRow);
                }
            }
        }
        if (eleccion == "d") {
            tableHeader.add("Nombre");
            tableHeader.add("Apellidos");
               String marca = "";
            String modelo = "";

          
            for (int i = 0; i < campos.length; i++) {
                Vector<String> onRow = new Vector<String>();
                if (i % 2 == 0) { 
                    marca = campos[i];
                } else {  
                    modelo = campos[i];

                    
                    onRow.add(marca);
                    onRow.add(modelo);
                    tableData.add(onRow);
                }
            }
        }

        jTable1.setModel(new DefaultTableModel(tableData, tableHeader));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxConsultas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
