import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author raull
 */
public class Modificaciones extends javax.swing.JPanel {

    private String eleccion;

    public Modificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaXML = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 204, 51));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        A.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(A);
        A.setText("Sustituir el valor del nodo kilómetros a 110000 en el producto cuya matrícula=6666FFF.");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        B.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(B);
        B.setText("Modificar el nombre del nodo kilómetros de cada vehículo de la colección vehículos por kms.");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        C.setBackground(new java.awt.Color(255, 204, 102));
        buttonGroup1.add(C);
        C.setText("Inserta una nueva reparación con los siguientes datos:");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        jLabel1.setText(" matrícula:3333CCC,  inicio:02/03/2025, mecánico: Lucas García -950456987.");

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setText("MODIFICAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTabbedPane1.addTab("tab1", jScrollPane3);

        jTextAreaXML.setColumns(20);
        jTextAreaXML.setRows(5);
        jScrollPane2.setViewportView(jTextAreaXML);

        jTabbedPane1.addTab("tab2", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B)
                            .addComponent(A)
                            .addComponent(C)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(A)
                .addGap(18, 18, 18)
                .addComponent(B)
                .addGap(18, 18, 18)
                .addComponent(C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        ConsultasBaseDatos actualizacion = new ConsultasBaseDatos();
        String rutaActualizacion = null;
        String rutaConsulta = null;
        boolean resultadoTextArea = false;

        if (A.isSelected()) {

            rutaActualizacion = "AD52425/Ejercicio03A.xq";
            rutaConsulta = "AD52425/EjercicioConsulta03A.xq";
        }
        if (B.isSelected()) {
            rutaActualizacion = "AD52425/Ejercicio03B.xq";
            rutaConsulta = "AD52425/EjercicioConsulta03B.xq";
            resultadoTextArea = true;
        }
        if (C.isSelected()) {
            rutaActualizacion = "AD52425/Ejercicio03C.xq";
            rutaConsulta = "AD52425/EjercicioConsulta03C.xq";
            resultadoTextArea = true;
        }
        String actualizar = actualizacion.leerArchivo(rutaActualizacion);
        String actualizarConsulta = actualizacion.leerArchivo(rutaConsulta);
        String resultado = actualizacion.Actualizar(actualizar, actualizarConsulta);
        if (resultadoTextArea) {
            jTextAreaXML.setText(resultado);
            System.out.println(resultado);
        } else {
            monstrarActualizacion(resultado);
        }

        System.out.println(resultado);

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        consultas("A");

    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        consultas("B");
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        consultas("C");
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_CActionPerformed
    private void consultas(String consulta) {
        eleccion = consulta;
        ConsultasBaseDatos actualizacion = new ConsultasBaseDatos();

        String ruta = "AD52425/EjercicioConsulta03" + consulta + ".xq";
        System.out.println(ruta);
        String actualizar = actualizacion.leerArchivo(ruta);
        String resultado = actualizacion.AbrirBaseDatos(actualizar);
        monstrarActualizacion(resultado);
    }

    private void monstrarActualizacion(String resultado) {
        Vector<String> tableHeader = new Vector<String>();
        Vector tableData = new Vector();
        String resultadoLimpio = resultado.replace("\n", " ");
        String[] campos = resultadoLimpio.split(" ");
        if (eleccion == "A") {
            tableHeader.add("Mátricula");
            tableHeader.add("Kilometros");

            String marca = "";
            String modelo = "";

            for (int i = 0; i < campos.length; i++) {
                Vector<String> onRow = new Vector<String>();
                if (i % 2 == 0) {
                    marca = campos[i];
                } else {
                    modelo = campos[i];

                    onRow.add(marca);
                    onRow.add(modelo);
                    tableData.add(onRow);
                }
            }
        }
        if (eleccion == "B") {
            jTextAreaXML.setText(resultado);
            System.out.println(resultado);

        }
        if (eleccion == "C") {
            jTextAreaXML.setText(resultado);
            System.out.println(resultado);
        }

        jTable1.setModel(new DefaultTableModel(tableData, tableHeader));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JRadioButton B;
    private javax.swing.JRadioButton C;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaXML;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
